# syntax=docker/dockerfile:1
# Based on https://github.com/vapor/template/blob/main/Dockerfile

FROM swift:6.3-bookworm AS build

ARG TARGETARCH

# Install OS updates
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y \
    && apt-get install -y libjemalloc-dev

WORKDIR /build
COPY Package.swift ./
COPY Package.resolved ./
RUN swift package resolve --force-resolved-versions

COPY Sources ./Sources
COPY Tests ./Tests
COPY data ./data
COPY public ./public

RUN mkdir /staging

RUN --mount=type=cache,id=swift-build-${TARGETARCH},target=/build/.build,sharing=locked \
    swift build \
        -c release \
        --product Runner \
        --static-swift-stdlib \
        --enable-experimental-prebuilts \
        -Xlinker -ljemalloc&& \
    # Copy main executable to staging area
    cp "$(swift build -c release --show-bin-path)/Runner" /staging && \
    # Copy resources bundled by SPM to staging area
    find -L "$(swift build -c release --show-bin-path)" -regex '.*\.resources$' -exec cp -Ra {} /staging \;


WORKDIR /staging

# Copy static swift backtracer binary to staging area
RUN cp "/usr/libexec/swift/linux/swift-backtrace-static" ./

# Copy runtime content into the staging area.
# Ensure that by default, neither the directory nor any of its contents are writable.
RUN [ -d /build/public ] && { mv /build/public ./public && chmod -R a-w ./public; } || true
RUN [ -d /build/data ] && { mv /build/data ./data && chmod -R a-w ./data; } || true

FROM debian:bookworm

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y \
    && apt-get -q install -y \
      libjemalloc2 \
      ca-certificates \
      # curl is used for health checks
      curl \
      tzdata \
      libcurl4 \
      libxml2 \
    && rm -r /var/lib/apt/lists/*

RUN groupadd --gid 1001 vapor \
    && useradd --create-home --system --skel /dev/null --home-dir /app vapor --uid 1001 --gid vapor

WORKDIR /app

COPY --from=build --chown=vapor:vapor /staging ./

# Provide configuration needed by the built-in crash reporter and some sensible default behaviors.
ENV SWIFT_BACKTRACE=enable=yes,sanitize=yes,threads=all,images=all,interactive=no,swift-backtrace=./swift-backtrace-static

USER vapor:vapor

EXPOSE 8080

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=20s \
    --retries=3 \
    CMD ["/usr/bin/curl", "--head", "--silent", "--output", "/dev/null", "--show-error", "--fail", "--max-time", "5", "http://localhost:8080/"]

ENTRYPOINT ["./Runner"]
CMD ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
