name: Trigger Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_ACCESS_TOKEN > GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short hash
        run: echo "##[set-output name=short-hash;]$(git rev-parse --short HEAD)"
        id: short-hash

      - name: Docker Build
        run: docker
          build .
          -t ghcr.io/josephduffy/josephduffy.co.uk:latest --secret=id=GITHUB_ACCESS_TOKEN,src=./GITHUB_ACCESS_TOKEN
          --build-arg "BUILD_DATE=$(date -u)"
          --build-arg "GIT_COMMIT=${{ steps.short-hash.outputs.short-hash }}"
          --build-arg "WEBSITE_URL=${WEBSITE_URL}"
          --build-arg "HCAPTCHA_SITE_KEY=3549990c-5b31-4c18-84b6-e7f57fcde61b"
        env:
          DOCKER_BUILDKIT: "1"
          WEBSITE_URL: "https://noanalytics.josephduffy.co.uk/"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: docker push ghcr.io/josephduffy/josephduffy.co.uk:latest

  build_image_analytics:
    name: Build Image with Analytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_ACCESS_TOKEN > GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short hash
        run: echo "##[set-output name=short-hash;]$(git rev-parse --short HEAD)"
        id: short-hash

      - name: Docker Build
        run: docker
          build .
          -t ghcr.io/josephduffy/josephduffy.co.uk:analytics --secret=id=GITHUB_ACCESS_TOKEN,src=./GITHUB_ACCESS_TOKEN
          --build-arg "BUILD_DATE=$(date -u)"
          --build-arg "GIT_COMMIT=${{ steps.short-hash.outputs.short-hash }}"
          --build-arg "WEBSITE_URL=${WEBSITE_URL}"
          --build-arg "ANALYTICS_URL=https://analytics.josephduffy.co.uk/"
          --build-arg "HCAPTCHA_SITE_KEY=3549990c-5b31-4c18-84b6-e7f57fcde61b"
          --build-arg "ENABLE_SITEMAP=TRUE"
        env:
          DOCKER_BUILDKIT: "1"
          WEBSITE_URL: "https://josephduffy.co.uk/"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: docker push ghcr.io/josephduffy/josephduffy.co.uk:analytics

  trigger_update:
    name: Trigger Update noanalytics.josephduffy.co.uk
    needs:
      - build_image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Simulate Webhook
        run: ./scripts/trigger-update-webhook.sh josephduffy-co-uk-no-analytics "${{ secrets.UPDATE_CONTAINER_SECRET }}" "${{ secrets.UPDATE_CONTAINERS_HOOK_URL }}"

  trigger_update_analytics:
    name: Trigger Update josephduffy.co.uk
    needs:
      - build_image_analytics
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Simulate Webhook
        run: ./scripts/trigger-update-webhook.sh josephduffy-co-uk "${{ secrets.UPDATE_CONTAINER_SECRET }}" "${{ secrets.UPDATE_CONTAINERS_HOOK_URL }}"

      - name: Ping Google
        run: curl "https://www.google.com/ping?sitemap=https://josephduffy.co.uk/sitemap.xml"

      - name: Ping Bing
        run: curl "https://www.bing.com/ping?sitemap=https://josephduffy.co.uk/sitemap.xml"
