name: Trigger Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_ACCESS_TOKEN > GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: noanalytics-docker-cache-{hash}
          restore-keys: |
            noanalytics-docker-cache-

      - name: Docker Build
        run: docker
          build .
          -t ghcr.io/josephduffy/josephduffy.co.uk:latest --secret=id=GITHUB_ACCESS_TOKEN,src=./GITHUB_ACCESS_TOKEN
          --build-arg "BUILD_DATE=$(date -u)"
          --build-arg "GIT_COMMIT=${GITHUB_SHA}"
          --build-arg "WEBSITE_URL=${WEBSITE_URL}"
          --build-arg "HCAPTCHA_SITE_KEY=3549990c-5b31-4c18-84b6-e7f57fcde61b"
        env:
          DOCKER_BUILDKIT: "1"
          WEBSITE_URL: "https://noanalytics.josephduffy.co.uk/"

      - name: Docker Login
        run: docker login ghcr.io -u "JosephDuffy" --password "${CR_PAT}"
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Docker Push
        run: docker push ghcr.io/josephduffy/josephduffy.co.uk:latest

  build_image_analytics:
    name: Build Image with Analytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_ACCESS_TOKEN > GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: analytics-docker-cache-{hash}
          restore-keys: |
            analytics-docker-cache-

      - name: Docker Build
        run: docker
          build .
          -t ghcr.io/josephduffy/josephduffy.co.uk:analytics --secret=id=GITHUB_ACCESS_TOKEN,src=./GITHUB_ACCESS_TOKEN
          --build-arg "BUILD_DATE=$(date -u)"
          --build-arg "GIT_COMMIT=${GITHUB_SHA}"
          --build-arg "WEBSITE_URL=${WEBSITE_URL}"
          --build-arg "ANALYTICS_URL=https://analytics.josephduffy.co.uk/"
          --build-arg "HCAPTCHA_SITE_KEY=3549990c-5b31-4c18-84b6-e7f57fcde61b"
        env:
          DOCKER_BUILDKIT: "1"
          WEBSITE_URL: "https://josephduffy.co.uk/"

      - name: Docker Login
        run: docker login ghcr.io -u "JosephDuffy" --password "${CR_PAT}"
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Docker Push
        run: docker push ghcr.io/josephduffy/josephduffy.co.uk:analytics

  trigger_update:
    name: Trigger Update
    needs:
      - build_image
      - build_image_analytics
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: JosephDuffy/webserver-deploy
          event-type: update_josephduffy-co-uk
