name: Trigger Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_ACCESS_TOKEN > GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Docker Build
        run: docker
          build .
          -t docker.pkg.github.com/josephduffy/josephduffy.co.uk/website:latest --secret=id=GITHUB_ACCESS_TOKEN,src=./GITHUB_ACCESS_TOKEN
          --build-arg "BUILD_DATE=$(date -u)"
          --build-arg "GIT_COMMIT=${GITHUB_SHA}"
          --build-arg "WEBSITE_URL=${WEBSITE_URL}"
        env:
          DOCKER_BUILDKIT: "1"
          WEBSITE_URL: "https://noanalytics.josephduffy.co.uk/"

      - name: Docker Login
        run: docker login docker.pkg.github.com -u "JosephDuffy" --password "${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: docker push docker.pkg.github.com/josephduffy/josephduffy.co.uk/website:latest

  build_image_analytics:
    name: Build Image with Analytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_ACCESS_TOKEN > GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Docker Build
        run: docker
          build .
          -t docker.pkg.github.com/josephduffy/josephduffy.co.uk/website:analytics --secret=id=GITHUB_ACCESS_TOKEN,src=./GITHUB_ACCESS_TOKEN
          --build-arg "BUILD_DATE=$(date -u)"
          --build-arg "GIT_COMMIT=${GITHUB_SHA}"
          --build-arg "WEBSITE_URL=${WEBSITE_URL}"
          --build-arg "ANALYTICS_URL=https://analytics.josephduffy.co.uk/"
        env:
          DOCKER_BUILDKIT: "1"
          WEBSITE_URL: "https://josephduffy.co.uk/"

      - name: Docker Login
        run: docker login docker.pkg.github.com -u "JosephDuffy" --password "${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: docker push docker.pkg.github.com/josephduffy/josephduffy.co.uk/website:analytics

  trigger_update:
    name: Trigger Update
    needs:
      - build_image
      - build_image_analytics
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: JosephDuffy/webserver-deploy
          event-type: update_josephduffy-co-uk
