name: Trigger Deploy

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo $GITHUB_ACCESS_TOKEN > GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short hash
        run: echo "##[set-output name=short-hash;]$(git rev-parse --short HEAD)"
        id: short-hash

      - name: Docker Build
        run: docker
          build .
          -t ghcr.io/josephduffy/josephduffy.co.uk:latest --secret=id=GITHUB_ACCESS_TOKEN,src=./GITHUB_ACCESS_TOKEN
          --build-arg "BUILD_DATE=$(date -u)"
          --build-arg "GIT_COMMIT=${{ steps.short-hash.outputs.short-hash }}"
          --build-arg "WEBSITE_URL=${WEBSITE_URL}"
          --build-arg "HCAPTCHA_SITE_KEY=3549990c-5b31-4c18-84b6-e7f57fcde61b"
        env:
          DOCKER_BUILDKIT: "1"
          WEBSITE_URL: "https://josephduffy.co.uk/"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: docker push ghcr.io/josephduffy/josephduffy.co.uk:latest

  trigger_webhook:
    name: Trigger Webhook
    runs-on: ubuntu-latest
    needs: [build_image]
    steps:
      - uses: actions/checkout@v3

      - name: Trigger Webhook
        run: ./scripts/trigger-update-webhook.sh "josephduffy.co.uk" "$WEBHOOK_SECRET" "$WEBHOOK_URL"
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
