name: Build project and Run Lighthouse CI

on: [pull_request]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse CI
        run: |
          docker build -t josephduffy:lighthouse --build-arg GITHUB_ACCESS_TOKEN .
          npx @lhci/cli@0.3.x autorun --collect.startServerCommand="docker run --rm -p 80:80 josephduffy:lighthouse" || echo "LHCI failed!"
          docker rmi --force josephduffy:lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
