name: Prune Registry

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  prune_registry:
    name: Prune Registry
    runs-on: ubuntu-latest
    steps:
      - name: Prune Untagged Images Older Than 7 Days
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: josephduffy.co.uk
          dry-run: false
          older-than: 7 # days
          untagged: true
